parent=base
import=common/keycloak

styles=css/style.css
# No common stylesheet for email theme by default, but we can define one if needed.
# Keycloak emails usually use inline styles for better compatibility.
